enum BUTTON_TAG {
	TAG_CANCEL,
	TAG_TIMER,
	TAG_COPY,
	TAG_RECORD,
	TAG_START_TIMER,
	TAG_PAUSE_TIMER,
	TAG_CANCEL_TIMER,
	TAG_PLUS_COUNT,
	TAG_MINUS_COUNT,
	TAG_RESET_COUNT,
	TAG_MENU,
	TAG_CONFIG,
	TAG_CONTINUOUS,
	TAG_COPY_CONTINUOUS,
	TAG_SELECTION_HISTORY,
	
	// for QL
	TAG_TRASH,
	TAG_PREFERENCE,
	TAG_RETAKE,
	TAG_APPLICATION,
	TAG_PREVIOUS_FILE,
	TAG_NEXT_FILE
};
